generation_config:
  model: "gemini-1.5-flash-001"
  max_output_tokens: 8192
  temperature: 0.2
  top_p: 0.95


safety_settings:
  - category: "HARM_CATEGORY_HATE_SPEECH"
    threshold: "BLOCK_NONE"
  - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
    threshold: "BLOCK_NONE"
  - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
    threshold: "BLOCK_NONE"
  - category: "HARM_CATEGORY_HARASSMENT"
    threshold: "BLOCK_NONE"